apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: eks-skaffold
build:
  artifacts:
  - image: public.ecr.aws/j2x1y3l5/skafold
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-service.yaml
